### ISSUE TITLE
Possible Issue: Locking colors

### ISSUE THREAD

**Issue by r0b0-s1av3** [r0b0-s1av3/color-generator#12]
There may be value in letting users lock a color so it can't be changed with a new generation. This could be as simple as a checkbox and having the generator function check to see if anything is locked before replacing.

**Comment by natehole** [comment]
Alternatively each color could be refreshed independently by adding a refresh option below each color.

**Comment by plin0009** [comment]
Both of these ideas are great and I think they can coexist.

**Comment by thekanbo** [comment]
I can work on these!

**Comment by r0b0-s1av3** [comment]
Thanks for all of the input, these are good ideas. Feel free to post more ideas/enhancements as you come across them.
