### ISSUE TITLE
Remove HTML from JS

### ISSUE THREAD

**Issue by thekanbo** [r0b0-s1av3/color-generator#6]
Javascript file should only include scripting, rather than templating; the HTML structure can be moved outside of the JS files and kept in the page index. The Javascript can then target the existing elements rather than generating and inserting new elements on load.

**Comment by r0b0-s1av3** [comment]
# TODO:
1. Create six-column layout in HTML file with default color values and unique selectors.
2. In the `generate()` function, change `for` loop to iterate through the columns and change the color values.

**Comment by thekanbo** [comment]
@r0b0-s1av3 please assign to me so I can take it!
